addicional credits for my friends that helped-me so much:{
-Dhummy
-Zevastica
-Rekalta
-ShiTist
}

Thank you so much to support my projects, i have a long way to go and by supporting-me u motivate-me to do incredible things

-UmaEra
Portuguese programmer 💛
