crb.new({process})[
  process.name: renderer
  process.filepath: ""
  process.age: NoN
  process.startname: renderer(){
    subcommands:
    name - crb.definition.name - execute_with: ""
    title - crb.defenition.title - execute with ""
    number - crb.defenition.number - execute with ""
    process.name - crb.defenition(process.name) - execute with ""
    }
  process.endname: renderer.delete;
  ]
    
    

  
